
# 网站标题 
title: meishadev's blog

# 网站副标题
subtitle: meishadevs的技术博客

# 网站描述 
description: 这个博客主要用来分享博主在Web前端开发领域中使用的技术和心得

# 网站作者
author: meishadevs

# 网站使用的语音
language: zh-CN

# 网站所在的时区
timezone:

# 网站的网址
url: http://meishadevs.com/

# 网站的根目录
root: /

# 生成的博客的存放目录
permalink: blog/:title/

# 永久链接中各部分的默认值
permalink_defaults:

# 资源文件夹，这个文件夹用来存放内容
source_dir: source

# 公共文件夹，这个文件夹用来存放生成的站点文件
public_dir: public

# 标签文件夹
tag_dir: tags

# 归档文件夹
archive_dir: archives

# 分类文件夹
category_dir: categories

# include code 文件夹
code_dir: downloads/code

# 国际化(i18n)文件夹
i18n_dir: :lang

# 跳过指定文件的渲染，您可使用 glob 表达式来匹配路径
skip_render:

# 新文章文件名称
new_post_name: :title.md

# 预设布局 
default_layout: post

# 把标题转换为 title case
titlecase: false

# 在新标签中打开链接
external_link: true 

# 把文件名称转换为(1)小写或(2)大写
filename_case: 0

# 显示草稿
render_drafts: false

# 启动 Asset 文件夹
post_asset_folder: false

# 把链接改为与根目录的相对位址
relative_link: false

# 显示未来的文章
future: true

# 代码块的设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# 搜索  
search:
  path: search.xml
  field: all
  
# RES  
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  
# 默认分类
default_category: uncategorized

# 分类别名
category_map:

# 标签别名
tag_map:

# 日期格式
date_format: YYYY-MM-DD

# 时间格式
time_format: HH:mm:ss

# 每页显示的文章量 (0 == 关闭分页功能)	
per_page: 5

# 分页目录
pagination_dir: page

# 禁用归档、标签、目录页面的分页功能
archive_generator:
  per_page: 0
tag_generator:
  per_page: 0
category_generator:
  per_page: 0
  
# 当前的主题名称
theme: raytaylorism

# 部署相关的设置
deploy:
  type: git
  repo: 
    github: git@github.com:meishadevs/meishadevs.github.io.git,master
    coding: git@git.coding.net:meishadevs/meishadevs.git,master
